config/routes.rb
SlinggitWebapp::Application.routes.draw do
  match 'users/set_no_thanks', :to => 'users#set_no_thanks', via: :get
  match 'users/reset_page_session', :to => 'users#reset_page_session', via: :get
  match 'users/verify_email_availability', :to => 'users#verify_email_availability', via: :post
  match 'users/verify_username_availability', :to => 'users#verify_username_availability', via: :post
  match 'users/update_email_and_send_verification', :to => 'users#update_email_and_send_verification', via: :put
  match '/edit_email_for_verification', :to => 'users#edit_user_email_for_verification', :as => 'prep_for_reverification'
  match 'networks/set_primary_account', :to => 'networks#set_primary_account', via: :post
  match 'posts/filtered_list', :to => 'posts#filtered_list'

  match 'users/email_preferences', :to => 'users#email_preferences'
  match 'users/enter_new_password/(:id)', :to => 'users#enter_new_password#id'
  match 'users/password_reset', :to => 'users#password_reset'
  match 'users/reactivate(/:id)', :to => 'users#reactivate#id', via: :get
  match 'users/destroy', :to => 'users#destroy', via: :delete
  match 'users/delete_account', :to => 'users#delete_account', via: :get
  match 'users/verify_email(/:id)', :to => 'users#verify_email#id'
  match 'users/new(/:id)', :to => 'users#new#id'
  match 'users/watching', :to => 'users#watching', as: "users_watching", via: :get
  match 'users/archived', to: 'users#archived', as: "users_archived", via: :get
  match 'networks/delete_account', :to => 'networks#delete_account', via: :post
  match 'networks/add_api_account(/:id)', :to => 'networks#add_api_account#id', via: :get
  match 'networks/twitter_callback', :to => 'networks#twitter_callback', via: :get
  match 'networks/facebook_callback', :to => 'networks#facebook_callback', via: :get
  match 'sessions/sign_out_of_device', :to => 'sessions#sign_out_of_device', via: :post
  match 'posts/results/(:id)', :to => 'posts#results#id', via: :get
  match 'posts/delete_post', :to => 'posts#delete_post'
  match 'posts/report_abuse(/:id)', :to => 'posts#report_abuse#id'
  match 'posts/repost(/:id)', :to => 'posts#repost#id'
  match 'posts/edit_field(/:id)', :to => 'posts#edit_field#id'
  match 'additional_photos/add', :to => 'additional_photos#add', :via => :post

  match 'watchedposts/interested', :to => 'watchedposts#interested'
  match 'watchedposts/uninterested', :to => 'watchedposts#uninterested'

  match 'messages/delete(/:id)', :to => 'messages#delete#id'
  match 'messages/delete_all', :to => 'messages#delete_all'
  match 'messages/new(/:id)', :to => 'messages#new#id'
  match 'messages/reply(/:id)', :to => 'messages#reply#id'
  match 'messages/sent', :to => 'messages#sent'

  resources :users
  resources :messages
  resources :sessions, only: [:new, :create, :destroy, :index]
  resources :posts, only: [:new, :create, :destroy, :edit, :show, :update]
  resources :networks, only: [:index, :create, :destroy]
  resources :watchedposts

  match '/twitter_callback', :to => 'twittersessions#callback', :as => 'callback'
  match '/facebook_callback', :to => 'facebooksessions#callback', :as => 'facebook_callback'
  match '/twitter_signup_callback', :to => 'users#twitter_signup_callback'
  match '/reauthorize_twitter', to: 'twittersessions#reauthorize'
  match '/create_reauthorization', to: 'twittersessions#create_reauthorization'
  match '/reauthorize_callback', to: 'twittersessions#reauthorize_callback'

  resources :twittersessions
  resource :facebooksessions

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/request_invitation', to: 'users#request_invitation', :as => 'request_invitation'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help', to: 'static_pages#help'
  match '/suspended_account', to: 'static_pages#suspended_account'
  match '/deleted_account', to: 'static_pages#deleted_account'
  match '/reactivate_account', to: 'static_pages#reactivate_account'
  match '/terms_of_service', to: 'static_pages#terms_of_service'

  resources :additional_photos
  resources :posts do
    resources :comments
  end
  match 'comments/delete(/:id)', :to => 'comments#delete#id'

  match 'mobile' => 'mobile#index'
  match 'mobile(/:action)(/:id)', :to => 'mobile#action#id'

  match 'admin' => 'admin#index', :as => :admin_dashboard
  match 'admin/users' => 'admin#view_users', :as => :admin_users
  match 'admin/users(/:id)' => 'admin#view_user#id', :as => :admin_user
  match 'admin/posts' => 'admin#view_posts', :as => :admin_posts
  match 'admin/post(/:id)', to: 'admin#view_post#id', :as => :admin_post
  match 'admin/comments' => 'admin#view_comments', :as => :admin_comments
  match 'admin/comment(/:id)', to: 'admin#view_comment#id', :as => :admin_comment
  match 'admin/view_database', to: 'admin#view_database', as: :admin_database
  match 'admin/problem_reports', to: 'admin#problem_reports', as: :admin_problem_reports
  match 'admin(/:action(/:id))' => 'admin#action#id'

  match 'test' => 'test#index'
  match 'test(/:action)(/:id)', :to => 'test#action#id'

  match 'backend/daily_jobs', :to => 'backend#daily_jobs'

  match '/maintenence', to: 'static_pages#maintenence', :as => 'maintenence'
  match '/over_capacity', to: 'static_pages#over_capacity', :as => 'over_capacity'

  match '*path', :to => 'application#redirect'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.paginate(page: params[:page], :per_page => 4, :conditions => ['open = ? AND status = ?', true, STATUS_ACTIVE], :order => 'id desc')
    if signed_in?
      @primary_twitter_account = ApiAccount.first(:conditions => ['user_id = ? AND status = ?', current_user.id, STATUS_PRIMARY])
    end
  end

  def about
  end

  def contact
    @name = params[:name]
    @email = signed_in? ? current_user.email : params[:email]
    @message = params[:message]
    if request.post?
      if not @name.blank?
        if not @email.blank?
          if not @message.blank?
            to = 'danlogan@slinggit.com,chrisklein@slinggit.com,philbeadle@slinggit.com,chasecourington@slinggit.com'
            from = 'Contact Us <noreply@slinggit.com>'
            subject = "Inquiry from #{@name}"
            content = "<p>Name: #{@name}<p/></br></br><p>Email: #{@email}</p></br></br><p>Message: #{@message}</p>"
            if signed_in?
              content << "<p>User was signed in with user_id: #{current_user.id} and their email is #{current_user.email_is_verified? ? 'verified' : 'not verified'}.</p>"
            end
            if not request.blank?
              content << "<p>User Agent: #{request.user_agent}</p>"
            end
            reply_to = @email
            UserMailer.generic_internal_email(to, from, subject, content, reply_to).deliver
            flash.now[:success] = "Thanks so much for your inquiry.  An email has been passed along to the Slinggit team."
            @name = @email = @message = ''
          else
            flash.now[:error] = "We would be tickled pink if you could throw together a quick message for us."
          end
        else
          flash.now[:error] = "Without an email address it may prove rather difficult to get in touch with you."
        end
      else
        flash.now[:error] = "We were hoping you could give us a name so we know who to address."
      end
    end
  end

  def help
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_terms_of_service.html.erb
<article class="row white_well">
<h2 class="bottom_border">
	Web Site Terms and Conditions of Use
</h2>

<h3>
	1. Terms
</h3>

<p>
	By accessing this Slinggit web site, you are agreeing to be bound by these 
	web site Terms and Conditions of Use, all applicable laws and regulations, 
	and agree that you are responsible for compliance with any applicable local 
	laws. If you do not agree with any of these terms, you are prohibited from 
	using or accessing this site. The contents contained in this web site are 
	protected by applicable copyright and trade mark law.
</p>

<h3>
	2. Use License
</h3>

<ol class="terms_parent">
	<li>
		Permission is granted to temporarily access and use the contents 
		(information or software) on Slinggit's web site for personal, 
		non-commercial use only. While using this web site, you may not:
		
		<ol class="terms_child">
			<li>modify or copy the contents;</li>
			<li>use the contents for any commercial purpose, or for any public display (commercial or non-commercial);</li>
			<li>attempt to decompile or reverse engineer any software contained on Slinggit's web site;</li>
			<li>remove any copyright or other proprietary notations from the contents; or</li>
			<li>transfer the contents to another person or "mirror" the contents on any other server.</li>
		</ol>
	</li>
	<li>
		Any redistribution or reproduction of part or all of the contents in any form is prohibited other than the following:
	</li>
		<ol class="terms_child">
			<li>you may print or download to a local hard disk extracts for your personal and non-commercial use only</li>
			<li>you may copy the content to individual third parties for their personal use, but only if you acknowledge the website as the source of the material</li>
		</ol>
	<li>
		This license shall automatically terminate if you violate any of these restrictions and may be terminated by Slinggit at any time.
	</li>
</ol>

<h3>
	3. Disclaimer
</h3>

<ol class="terms_parent">
	<li>
		The contents on Slinggit's web site are provided "as is". Slinggit makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Slinggit does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the contents on its Internet web site or otherwise relating to such contents or on any sites linked to this site.
	</li>
</ol>

<h3>
	4. Limitations
</h3>

<p>
	In no event shall Slinggit be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the contents on Slinggit's Internet site, even if Slinggit or a Slinggit authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
</p>
			
<h3>
	5. Revisions and Errata
</h3>

<p>
	The contents appearing on Slinggit's web site could include technical, typographical, or photographic errors. Slinggit does not warrant that any of the contents on its web site are accurate, complete, or current. Slinggit may make changes to the contents contained on its web site at any time without notice. Slinggit does not, however, make any commitment to update the contents.
</p>

<h3>
	6. Links
</h3>

<p>
	Slinggit has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Slinggit of the site. Use of any such linked web site is at the user's own risk.
</p>

<h3>
	7. Site Terms of Use Modifications
</h3>

<p>
	Slinggit may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
</p>

<h3>
	8. Governing Law
</h3>

<p>
	Any claim relating to Slinggit's web site shall be governed by the laws of the State of COLORADO (CO) without regard to its conflict of law provisions.
</p>

<p>
	General Terms and Conditions applicable to Use of a Web Site.
</p>
</article>

<article class="row white_well">
<h2>
	Privacy Policy
</h2>

<p>
	Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
</p>

<ul class="terms_parent">
	<li>
		Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
	</li>
	<li>
		We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.		
	</li>
	<li>
		We will only retain personal information as long as necessary for the fulfillment of those purposes. 
	</li>
	<li>
		We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. 
	</li>
	<li>
		Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. 
	</li>
	<li>
		We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
	</li>
	<li>
		We will make readily available to customers information about our policies and practices relating to the management of personal information. 
	</li>
</ul>

<p>
	We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. 
</p>	
</article>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<section class="wrapper aboutUs">
	
<div class="row white_well">
	
	<header class="row bottom_border">
		<h1>About Slinggit</h1>
	</header>
	
	<article class="col3 pull_left well">
		<p>Slinggit is built in sunny Denver, CO.  We're using the best technologies available to us to give you a streamlined experience and help you close transactions faster than on any other e-comm platform out there. </p>
		<p>It’s no secret that social networks are a key component in the modern e-commerce platform.  We know Slinggit isn't your only option, however, we believe we have a unique and highly effective offering in this young and growing space.</p>
		<p>Our mission is simple, it’s to be the fastest way for you to find and buy the things you want and sell the things you don't.  Yep, it's that simple.  We hope you’ll give Slinggit a go!</p>
	</article>
	
<!-- PROFILES -->
	<aside class="col3 pull_right grey_well">
		
		<header class="row bottom_border">
			<h1>The guys behind Slinggit are&hellip;</h1>
		</header>
		
		<div class="row">
			<figure class="col2 pull_left img_border">
				<%= image_tag('aboutUs/profile_chris_180x180.jpg', width: '100%', height: 'auto', title: 'Chris Klein', alt: 'Picture of Chris Klein') %>
				<a href="https://twitter.com/_chrisklein" title="@_chrisklein" class="ss-twitter ss-social">@_chrisklein</a>
			</figure>
			<figcaption class="col4 pull_right">Chris Klein <span class="top_border">Javascript, Ruby, whatever it takes.  CEO.  Ohio Buckeye. Graduate of The Ohio State University and University of Denver.  Passion for building things he thinks people need.  Thinks this is one of them.  Lives in Denver, CO with wife, dog and cat.</span></figcaption>
		</div>
		
		<div class="row">
			<figure class="col2 pull_left img_border">
				<%= image_tag('aboutUs/profile_phil_180x180.jpg', width: '100%', height: 'auto', title: 'Phil Beadle', alt: 'Picture of Phil Beadle') %>
				<a href="https://twitter.com/philslinggit" title="@philslinggit" class="ss-twitter ss-social">@philslinggit</a>
			</figure>
			<figcaption class="col4 pull_right">Phil Beadle <span class="top_border">iOS and Android. VP of Mobile. I don&rsquo;t always sell my stuff, but when I do I prefer Slinggit.</span></figcaption>
		</div>
		
		<div class="row">
			<figure class="col2 pull_left img_border">
				<%= image_tag('aboutUs/profile_dan_180x180.jpg', width: '100%', height: 'auto', title: 'Dan Logan', alt: 'Picture of Dan Logan') %>
				<a href="https://twitter.com/danclogan" title="@danclogan" class="ss-twitter ss-social">@danclogan</a>
			</figure>
			<figcaption class="col4 pull_right">Dan Logan <span class="top_border">Rails guru. CTO. Montana mountain man now living in Centennial, CO.  StarCraft II junkie.  World's #1 ATB fan. Broncos for life. Looking forward to slingging Broncos tickets to friends.</span></figcaption>
		</div>		
		
		<div class="row">
			<figure class="col2 pull_left img_border">
				<%= image_tag('aboutUs/profile_chase_180x180.jpg', width: '100%', height: 'auto', title: 'Chase Courington', alt: 'Picture of Chase Courington') %>
				<a href="https://twitter.com/ChaseCourington" title="@chasecourington" class="ss-twitter ss-social">@chasecourington</a>
			</figure>
			<figcaption class="col4 pull_right">Chase Courington <span class="top_border">HTML/CSS. VP of UX. Craft beer, typography and responsive design. Has a garage full of snowboarding gear to sling. Lives in Denver, CO with his wife.</span></figcaption>
		</div>
		
	</aside>
<!-- END -->

</div>
</section>	

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<section class="wrapper contactUs">

  

  <article class="row main">
	<header class="row">
	    <h1 class="bottom_border">Contact</h1>
	  </header>
    <p>Thank you for your interest in Slinggit. We look forward to hearing from you.</p>

    <%= form_tag(url_for(:controller => :static_pages, :action => :contact), :class => "col4 offset1 grey_well") do %>

        <fieldset class="row">
          <label class="col3 pull_left">Name:</label>
          <%= text_field_tag :name, @name, :class => "col6 pull_left", :placeholder => 'Name' %>
        </fieldset>

        <% if not signed_in? %>
            <fieldset class="row">
              <label class="col3 pull_left">Email Address:</label>
              <%= email_field_tag :email, @email, :class => "col6 pull_left", :placeholder => 'Email' %>
            </fieldset>
        <% end %>

        <fieldset class="row">
          <label class="col3 pull_left">Message:</label>
          <%= text_area_tag :message, @message, :class => "col6 pull_left", :placeholder => 'Message' %>
        </fieldset>

        <fieldset class="row">
          <button type="submit" class="col2 btn_green">Send</button>
        </fieldset>

    <% end %>

  </article>
</section>

app/views/static_pages/deleted_account.html.erb
<% provide(:title, 'Banned') %>
<header class="row">
	<h1 class="col4 offset1">You have been banned so hard!</h1>
</header>

<div class="row">
	<p class="col4 offset1">If you feel you have reached this page in error, please contact customer support.</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<section class="wrapper getHelp">
	<header class="row">
		<h1 class="bottom_border">Help</h1>
	</header>
	
	<div class="col3 pull_left grey_well">
		
		<article class="row">
			<div class="col6 white_well">
				<h2 class="bottom_border">How it Works</h2>
				<p>Slinggit is a free web application that can be accessed from your desktop, laptop and mobile device.  We have a free iOS app available as well.  With it you can buy from and sell to your friends, followers and searching buyers. Slinggit leverages features in common social networks that you're already familiar with to greatly speed up the transaction process.  From Slinggit you can make a single post that is shared across your social networks.  You may ask questions about posted items and see what others have asked.  You can also interact directly and privately with buyers and sellers alike.  You'll have insight into how many people are interested in a item at any given time.  You can provide feedback to help sell future items.  Slinggit is highly interactive and simple to use.  It's the fastest way to git the things you want and sling the things you don't.</p>
			</div>
		</article>
		
		<article class="row">
			<div class="col6 white_well">
				<h2 class="bottom_border">Buying</h2>
				<p>Slinggit postings can be found in Twitter and Facebook searches based on location and item.  They can be found in your Facebook and Twitter friends' feeds.  They are also posted to the Slinggit Twitter, Facebook and application feeds.  You can communicate directly with the seller through your social networks or follow the post back to Slinggit to see the full details and engage the seller there.  Post details include photos, public questions and tracking of interested buyers. You are free to ask questions, engage the seller privately, or simply take an interest and watch how things play out.  The sales transaction is up to you and the seller to complete. Cash, paypal, barter, whatever.  You know how to get a deal done.</p>
			</div>
		</article>	
		
		<article class="row">
			<div class="col6 white_well">
				<h2 class="bottom_border">Selling</h2>
				<p>Selling with Slinggit is fast, easy and controlled.  It's fast in that we encourage brevity and clarity in your post.  It's faster in that we've created a mobile optimized platform for you to create your brief and clear posts.  It's even faster in that with a click of a button this post is broadcast to your social networks of choice.  It's easy because this can all be done from most any device all on one screen.  It's controlled in that we encourage feedback from buyers to sellers and we move the sales cycle along, gently encouraging you to close your sale and helping you as much as possible to do so.  A fresh marketplace keeps people coming back and keeps you selling.  Remember, not all things are appropriate for sale on Slinggit for a variety of reasons.  Please use your best judgement when posting.  Finally, it's controlled in that Slinggit has plans of action and safeguards in place to keep the market fresh, relevant, and free of inappropriate content.</p>
			</div>
		</article>
		
		<article class="row">
			<div class="col6 white_well">
				<h2 class="bottom_border">Convention</h2>
				<p>You'll notice that Slinggit posts have #hashtags. The hastag allows that post to be searchable through Twitter and Facebook, increasing the chance that your item is found by a buyer.  We believe that the more simple and common an item's name and location are the better chance it has of being exposed to a larger buyer market. Take the following example:</p>
				<p class="col4 offset1 white_well">#156cmsnowboardforsale</p>
				<p>That's pretty descriptive but someone has to be very specific with their search term to find it. A better item name might be: </p>
				<p class="col4 offset1 white_well">#snowboardforsale</p>
				<p>Now the item is much more findable and the details can be brought out through the item description.</p>
				<p>Items also get # for location.  This allows potential buyers to narrow their search by locality.  For example, you might name your item snowboard and set your location as Denver.  A potential buyer searching for the following would find your item:</p>
				<p class="col4 offset1 white_well">#snowboardforsale #denver</p>
				<p>Did you know you can save searches in Twitter?  So if you're looking for, say, a snowboard in denver, you can save that search and easily return to it at anytime.  You can even keep that search up in a browser or your favorite tweet aggregator and see postings pop up in real time.</p>
			</div>
		</article>
		
	</div>
	
	<div class="col3 pull_right grey_well">
		
		<article class="row">
			<div class="col6 white_well">
				<h2 class="bottom_border">Mobile</h2>
				<p>We have designed and built Slinggit specifically to be used with mobile devices.   We have a free, native iOS app for iPhone users and our mobile web site is extremely lightweight and fully functional for Android and Windows Phone users.  Quickly snap photos or use existing ones from your mobile gallery, add an appropriate, searchable name and a concise description, then share it with your social networks of choice.  Done.  Our mission is to give you a highly functional and easy to use product that may be light on the bling, but makes up for it in all around speed of sale.</p>
			</div>
		</article>
		
		<article class="row">
			<div class="col6 white_well">
				<h2 class="bottom_border">Accounts</h2>
				<p>When you sign up with Slinggit you can connect your Twitter account right away. Don't worry if you forgot, you can always add it later. You don't need Twitter and/or Facebook to use Slinggit, but we highly recommend it as your social networks provide the platform you need to significantly shorten the sales cycle.  You may add more accounts at anytime.  We allow you to add multiple Twitter accounts in the event you have more than one, possibly for use in your business.</p>
			</div>
		</article>
		
		<article class="row">
			<div class="col6 white_well">
				<h2 class="bottom_border">Security</h2>
				<p>HTTPS everywhere (except the blog, it's hosted by Tumblr). We use the secure APIs supplied by Facebook and Twitter to connect and we don't pry into your personal data. We will never spam or sell your email address. We regard security very highly and make sure to take all precautions. We recommend you do the same when dealing with buyers/sellers you do not know.</p>
			</div>
		</article>	
		
		<article class="row">
			<div class="col6 white_well">
				<h2 class="bottom_border">Contact</h2>
				<p>We appreciate questions, comments and feedback that help us provide you with a better product experience. We're working on gathering feedback to create an FAQ that we'll roll into the next build. <%= link_to "Get in touch!", contact_path %></p>
			</div>
		</article>
		
	</div>
	
</section>	

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<!-- if user is not signed in -->
    <% if current_user.blank? %>
<section class="homepage row">
		<!-- <div class="row grey_back"></div> -->
    	<div class="wrapper">
    		<h1 class="row">Sell to people you know. <span>Buy from people you trust.</span></h1>
    		<section class="row">
				<article class="col3 pull_right">
					<header class="row">
						<h1>A safer way to buy &amp; sell items online.</h1>
						<p>Quickly connect with friends and followers to make deals with people you already know and trust.</p>
					</header>
					<div class="row">
						<%= link_to "Try Slinggit", signup_path, class: "col6 btn_green" %>
					</div>
					<!--<div class="app-link col4 offset1">-->
					<a href="http://itunes.apple.com/us/app/slinggit/id543458895?mt=8&uo=4" target="itunes_store" title="iOS App Store" class="app-link btn_darkGrey row">
						<span class="col1 pull_left ss-cell"></span>
						<span class="col5 pull_right">Get the iPhone App</span>
					</a>
					<!--</div>-->
				</article>
				<figure class="col3 pull_left">
					<%= image_tag "heroimages/iOS_safari_bike_320x621.png", width: "100%", height: "auto", title: "Slinggit on your mobile device", alt: "Slinggit on iOS Safari" %>
				</figure>
				<p class="row">No more dealing with scammers and strangers. With Slinggit you can quickly sell to your friends or the greater community. It's up to you.</p>
			</section>
			<section class="row">
				<div class="col6 well_padding">
					<aside class="row">
						<div class="col2 pull_left">
							<figure class="white_well">
								<div class="row">
									<span class="ss-facebook ss-social-circle col3 pull_left"></span>
									<span class="ss-twitter ss-social-circle col3 pull_left"></span>
								</div>
								<figcaption class="row">Connect your Facebook and Twitter to send posts to your friends and followers. You also have the option to post to Slinggit's public feeds.</figcaption>
							</figure>
						</div>
						<div class="col2 pull_left">
							<figure class="white_well">
								<div class="row">
									<span class="ss-location col6"></span>
								</div>
								<figcaption class="row">Post an item based on your location (town, city, zip code) allowing friends and people in your community to buy your item. Keep it local!</figcaption>
							</figure>
						</div>
						<div class="col2 pull_left">
							<figure class="white_well">
								<div class="row">
									<span class="ss-cell col3 pull_left"></span>
									<span class="ss-desktop col3 pull_left"></span>
								</div>
								<figcaption class="row">Slinggit is built with web standards. This means Slinggit is available to anyone with internet, regardless of device. We love the web!</figcaption>
							</figure>
						</div>
					</aside>
				</div>
			</section>

		</div>
	<div class="color_block"></div>
<!-- if user is signed in -->
	<% elsif not current_user.blank? %>
<section class="wrapper homepage">

		<section class="secondary">
    		<div class="secondary_inner">
    			<%= render 'shared/user_info' %>
    		</div>

    		<div class="secondary_inner">
				<div class="row">
					<%= link_to "New Post", new_post_path, class: "ss-compose col3 pull_left btn_green" %>
					<%= link_to "My Posts", current_user, class: "ss-notebook col3 pull_right btn_ltGrey" %>
				</div>
				<div class="row wrong-user">
					<%= link_to signout_path, method: "delete", class: "pull_right" do %>
						<span>Not <%= current_user.name %>?</span> Sign Out.
					<% end %>
				</div>
    		</div>
    	</section>

    	<section class="main">
    		<% if !@posts.blank? %>
		        <article class="row home_featurePost">
		            <div  id="featuredPosts" class="col6">
						<h1 class="row">Recent Posts:</h1>
						<%= render @posts %>
					</div>
		        </article>
		    <% end %>
    	</section>
	<% end %>
</section>

app/views/static_pages/maintenence.html.erb
<% provide(:title, 'Home') %>
<section class="wrapper homepage">
Maintenence Mode
</section>

app/views/static_pages/over_capacity.html.erb
<% provide(:title, 'Home') %>
Over Capacity
</section>

app/views/static_pages/reactivate_account.html.erb
<% provide(:title, 'Contact') %>
<div class="row">
	<div class="col4 offset1">
		<h1 class="row">Considering coming back?</h1>
	</div>

	<div class="col4 offset1">
		<h4 class="row">Reactivation is easy</h4>
		<p class="row">Placeholder for user reactivation request.</p>
	</div>
</div>

app/views/static_pages/suspended_account.html.erb
<% provide(:title, 'Contact') %>
<div class="row">
	<div class="col4 offset1">
		<h1 class="row">Your have been placed in time out due to a terms of service violation.</h1>
		<p class="row">If you feel you have reached this page in error, please contact customer support.</p>
	</div>
</div>

app/views/static_pages/terms_of_service.html.erb
<% provide(:title, 'Terms of Service') %>

<section class="wrapper termsOfService">
	<header>
		<h1 class="bottom_border row">Terms of Service</h1>
	</header>
	<%= render "static_pages/terms_of_service" %>
</section>