config/routes.rb
SlinggitWebapp::Application.routes.draw do
  match 'users/set_no_thanks', :to => 'users#set_no_thanks', via: :get
  match 'users/reset_page_session', :to => 'users#reset_page_session', via: :get
  match 'users/verify_email_availability', :to => 'users#verify_email_availability', via: :post
  match 'users/verify_username_availability', :to => 'users#verify_username_availability', via: :post
  match 'users/update_email_and_send_verification', :to => 'users#update_email_and_send_verification', via: :put
  match '/edit_email_for_verification', :to => 'users#edit_user_email_for_verification', :as => 'prep_for_reverification'
  match 'networks/set_primary_account', :to => 'networks#set_primary_account', via: :post
  match 'posts/filtered_list', :to => 'posts#filtered_list'

  match 'users/email_preferences', :to => 'users#email_preferences'
  match 'users/enter_new_password/(:id)', :to => 'users#enter_new_password#id'
  match 'users/password_reset', :to => 'users#password_reset'
  match 'users/reactivate(/:id)', :to => 'users#reactivate#id', via: :get
  match 'users/destroy', :to => 'users#destroy', via: :delete
  match 'users/delete_account', :to => 'users#delete_account', via: :get
  match 'users/verify_email(/:id)', :to => 'users#verify_email#id'
  match 'users/new(/:id)', :to => 'users#new#id'
  match 'users/watching', :to => 'users#watching', as: "users_watching", via: :get
  match 'users/archived', to: 'users#archived', as: "users_archived", via: :get
  match 'networks/delete_account', :to => 'networks#delete_account', via: :post
  match 'networks/add_api_account(/:id)', :to => 'networks#add_api_account#id', via: :get
  match 'networks/twitter_callback', :to => 'networks#twitter_callback', via: :get
  match 'networks/facebook_callback', :to => 'networks#facebook_callback', via: :get
  match 'sessions/sign_out_of_device', :to => 'sessions#sign_out_of_device', via: :post
  match 'posts/results/(:id)', :to => 'posts#results#id', via: :get
  match 'posts/delete_post', :to => 'posts#delete_post'
  match 'posts/report_abuse(/:id)', :to => 'posts#report_abuse#id'
  match 'posts/repost(/:id)', :to => 'posts#repost#id'
  match 'posts/edit_field(/:id)', :to => 'posts#edit_field#id'
  match 'additional_photos/add', :to => 'additional_photos#add', :via => :post

  match 'watchedposts/interested', :to => 'watchedposts#interested'
  match 'watchedposts/uninterested', :to => 'watchedposts#uninterested'

  match 'messages/delete(/:id)', :to => 'messages#delete#id'
  match 'messages/delete_all', :to => 'messages#delete_all'
  match 'messages/new(/:id)', :to => 'messages#new#id'
  match 'messages/reply(/:id)', :to => 'messages#reply#id'
  match 'messages/sent', :to => 'messages#sent'

  resources :users
  resources :messages
  resources :sessions, only: [:new, :create, :destroy, :index]
  resources :posts, only: [:new, :create, :destroy, :edit, :show, :update]
  resources :networks, only: [:index, :create, :destroy]
  resources :watchedposts

  match '/twitter_callback', :to => 'twittersessions#callback', :as => 'callback'
  match '/facebook_callback', :to => 'facebooksessions#callback', :as => 'facebook_callback'
  match '/twitter_signup_callback', :to => 'users#twitter_signup_callback'
  match '/reauthorize_twitter', to: 'twittersessions#reauthorize'
  match '/create_reauthorization', to: 'twittersessions#create_reauthorization'
  match '/reauthorize_callback', to: 'twittersessions#reauthorize_callback'

  resources :twittersessions
  resource :facebooksessions

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/request_invitation', to: 'users#request_invitation', :as => 'request_invitation'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help', to: 'static_pages#help'
  match '/suspended_account', to: 'static_pages#suspended_account'
  match '/deleted_account', to: 'static_pages#deleted_account'
  match '/reactivate_account', to: 'static_pages#reactivate_account'
  match '/terms_of_service', to: 'static_pages#terms_of_service'

  resources :additional_photos
  resources :posts do
    resources :comments
  end
  match 'comments/delete(/:id)', :to => 'comments#delete#id'

  match 'mobile' => 'mobile#index'
  match 'mobile(/:action)(/:id)', :to => 'mobile#action#id'

  match 'admin' => 'admin#index', :as => :admin_dashboard
  match 'admin/users' => 'admin#view_users', :as => :admin_users
  match 'admin/users(/:id)' => 'admin#view_user#id', :as => :admin_user
  match 'admin/posts' => 'admin#view_posts', :as => :admin_posts
  match 'admin/post(/:id)', to: 'admin#view_post#id', :as => :admin_post
  match 'admin/comments' => 'admin#view_comments', :as => :admin_comments
  match 'admin/comment(/:id)', to: 'admin#view_comment#id', :as => :admin_comment
  match 'admin/view_database', to: 'admin#view_database', as: :admin_database
  match 'admin/problem_reports', to: 'admin#problem_reports', as: :admin_problem_reports
  match 'admin(/:action(/:id))' => 'admin#action#id'

  match 'test' => 'test#index'
  match 'test(/:action)(/:id)', :to => 'test#action#id'

  match 'backend/daily_jobs', :to => 'backend#daily_jobs'

  match '/maintenence', to: 'static_pages#maintenence', :as => 'maintenence'
  match '/over_capacity', to: 'static_pages#over_capacity', :as => 'over_capacity'

  match '*path', :to => 'application#redirect'

end

app/views/admin/index.html.erb
<% provide(:title, 'Admin') %>
<div class="wrapper">
  <div class="page_col twoCol">
    <header>
      <h1>Admin Tools</h1>
    </header>
    <div id='adminIndexList'>
      <h3>View:</h3>
      <ul class="adminList">
        <li><a href="/admin/view_images">Uploaded Images</a></li>
        <li><a href="<%= admin_users_path  %>">Users</a></li>
        <li><a href="/admin/view_invitations">Invitations</a></li>
      </ul>
      <h3>Problem Reports:</h3>
      <ul class="adminList">
        <li><a href="/admin/problem_reports">View Exceptions</a></li>
      </ul>
      <!-- TODO IMPLEMENT -->
      <!--<ul class="adminList">-->
      <!--<li><a href="/admin/view_users">View/Search Users</a></li>-->
      <!--<li><a href="#">View/Search Posts</a></li>-->
      <!--<li><a href="#">Manage Admin Accounts</a></li>-->
      <!--<li><a href="#">Manage User Limitations</a></li>-->
      <!--<li><a href="#">Manage Invitations</a></li>-->
      <!--</ul>-->
    </div>
  </div>
</div>

app/views/admin/problem_reports.html.erb
<div class="row wrapper adminSection">  
  <h1>View Problem Reports</h1>

  <div id="notice"></div>
  <table class="admin_table table_bordered table-striped">
    <thead>
    <th>Exception</th>
    <th>Class</th>
    <th>Status</th>
    <th>Occured At</th>
    <th>Last Updated By</th>
    <th>Last Updated At</th>
    <th>Owned By</th>
    <th>Actions</th>
    </thead>
    <tbody>
    <% @problem_reports.each do |problem_report| %>
        <tr>
          <td><%= problem_report.exception_message %></td>
          <td><%= problem_report.exception_class %></td>
          <td><%= problem_report.status %></td>
          <td><%= problem_report.created_at.strftime("%m/%d/%Y") %></td>
          <td><%= problem_report.last_updated_by_name %></td>
          <td><%= problem_report.updated_at.strftime("%m/%d/%Y") %></td>
          <td><%= problem_report.owner_name %></td>
          <td><a href="/admin/view_problem_report/<%= problem_report.id %>">wiew details</a> | <a href="/admin/problem_reports/<%= problem_report.id %>">close</a></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/view_comment.html.erb
<section class="row wrapper adminSection">

	<div class="white_well col2 pull_right">
	    <div class="row admin_controlls">
	    	<% if @comment.status == "ACT" or @comment.status == "BAN" %>
	    		<%= link_to "Delete", {:controller => :admin, :action => :set_comment_status, :id => @comment.id, :status => "DEL" }, confirm: "Delete Post: You sure?", class: "col6 btn_red" %>

	    	<% elsif @comment.status == "DEL" %>
	    		<%= link_to "Allow", {:controller => :admin, :action => :set_comment_status, :id => @comment.id, :status => "ACT" }, confirm: "Reenable Post: You sure?", class: "col6 btn_green" %>

	    	<% end %>
	    </div>
	</div>

	<div class="white_well col4">

		<header class="row">
			<h1>Comment (<%= @comment.id %>)</h1>
		</header>
		<article class="row">
			<div class="col3 pull_left">
				<p><%= @comment.body %>
			</div>

			<div class="col3 pull_right">
				<h4>Comment by: <%= link_to @comment.user.name, admin_user_path(@comment.user_id) %></h4>
				<h4>Belongs to Post: <%= link_to @comment.post.hashtag_prefix, admin_post_path(@comment.post_id) %></h4>
				<h4>Posted at: <%= link_to @comment.post.hashtag_prefix, post_path(@comment.post_id) %></h4>
			</div>

		</article>

	</div>
</section>

app/views/admin/view_comments.html.erb
<div class="row wrapper adminSection">
  <h1>All Comments</h1>

  <div class="row">
  <%= will_paginate @comments%>
  </div>

  <section>
    <table class="admin_table table_bordered table-striped">
      <thead>
        <tr>
          <th></th>
          <th>Content</th>
          <th>Post</th>
          <th>User</th>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.id %></td>
            <td><%= link_to comment.body, {:controller => :admin, :action => :view_comment, :id => comment.id} %></td>
            <td><%= link_to comment.post.hashtag_prefix, {:controller => :admin, :action => :view_post, :id => comment.post.id} %></td>
            <td><%= link_to comment.user.name, {:controller => :admin, :action => :view_user, :id => comment.user.id} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>

  <div class="row">
  <%= will_paginate @comments%>
  </div>
</div>

app/views/admin/view_images.html.erb
<h1>View Uploaded Images</h1>

<div id="errorDiv"></div>
<% if not @image_datas.blank? %>
    <div id="imageContent"></div>
<% else %>
    <div>No Images Available</div>
<% end %>


<script type="text/javascript">

    <% @image_datas.each do |image_data| %>
        window.createPhotoArticle(
            $('#imageContent'), 
            "<%= image_data[:image_path] %>",
            "<%= image_data[:post_id] %>",
            "<%= url_for :controller => :admin, :action => :eradicate_all_from_image %>"
        ).render()
    <% end %>

</script>


<!-- Chase feel free to delete these when you style this to work on mobile as well. -->

<style type="text/css">
    a {
        float: left;
        padding: 1px;;
    }

    #workingDiv {
        font-size: 20px;
        color: red;
        text-decoration: blink;
        margin-bottom: 20px;
    }

    #errorDiv {
        font-size: 20px;
        color: red;
        margin-bottom: 20px;
    }

    #doneDiv {
        font-size: 20px;
        color: green;
        margin-bottom: 20px;
    }
</style>

app/views/admin/view_invitations.html.erb
<div>
  <% if not @invitations.blank? %>
      <% @invitations.each do |invitation| %>
          <li>
            <%= invitation.email %>
            | <%= link_to "approve", {:controller => :admin, :action => :approve_invitation, :id => invitation.id}, confirm: "Approve: You sure?" %>
          </li>
      <% end %>
  <% else %>
    No invitations found.
  <% end %>
</div>

app/views/admin/view_post.html.erb
<section class="row wrapper adminSection">
	<div class="white_well col2 pull_right">
	    <div class="row admin_controlls">
	    	<% if @post.status == "ACT" or @post.status == "BAN" %>
	    		<%= link_to "Delete", {:controller => :admin, :action => :set_post_status, :id => @post.id, :status => "DEL" }, confirm: "Delete Post: You sure?", class: "col6 btn_red" %>

	    	<% elsif @post.status == "DEL" %>
	    		<%= link_to "Reenable", {:controller => :admin, :action => :set_post_status, :id => @post.id, :status => "ACT" }, confirm: "Reenable Post: You sure?", class: "col6 btn_green" %>

	    	<% end %>
	    </div>
	</div>

	<div class="white_well col4 pull_left">

		<header class="row">
			<h1>POST (<%= @post.hashtag_prefix %>)</h1>
		</header>
		<article class="row">
			<div class="col3 pull_left">
				<% if @post.photo_file_name.blank? %>
			        <div id="placeholderWrapper">
			          <%= image_tag "noPhoto_300x300.png", :id => "placeholderImg", :height => "auto", :width => "100%" %>
			      <% else %>
			          <%= image_tag @post.photo.url(:medium), :class => "img_border", :height => "auto", :width => "100%", :id => 'post_mainImage' %>
			      <% end %>

			</div>
			<div class="col3 pull_right">
				<p><%= @post.content %></p>
				<h4>Posted by: <%= link_to @post.user.name, {:controller => :admin, :action => :view_user, :id => @post.user_id} %></h4>
				<h4>Posted at: <%= link_to @post.hashtag_prefix, post_path(@post.id) %></h4>
			</div>
		</article>

		<div class="row">

	      <h3>Comments (<%= @post.comments.count %>) </h3>

	      <section>
	        <table class="admin_table table_bordered table-striped">
	          <thead>
	            <tr>
	              <th></th>
	              <th>Content</th>
	              <th>Post</th>
	              <th>Status</th>
	            </tr>
	          </thead>
	          <tbody>
	            <% @post.comments.each do |comment| %>
	              <tr>
	                <td><%= comment.id %></td>
	                <td><%= link_to comment.body, {:controller => :admin, :action => :view_comment, :id => comment.id} %></td>
	                <td><%= link_to comment.post.hashtag_prefix, {:controller => :admin, :action => :view_post, :id => comment.post.id} %></td>
	                <td><%= comment.status %></td>
	              </tr>
	            <% end %>
	          </tbody>
	        </table>
	      </section>

	    </div>

	</div>
</section>

app/views/admin/view_posts.html.erb
<div class="row wrapper adminSection">  
  <h1>All Posts</h1>

  <div class="row">
  <%= will_paginate @posts%>
  </div>

  <section>
    <table class="admin_table table_bordered table-striped">
      <thead>
        <tr>
          <th></th>
          <th>Item</th>
          <th>Photo</th>
          <th>User</th>
          <th>Comments</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.id %></td>
            <td><%= link_to post.hashtag_prefix, {:controller => :admin, :action => :view_post, :id => post.id} %></td>
            <td>
              <% if post.photo_file_name.blank? %>
                <%= image_tag "noPhoto_80x80.png" %>
              <% else %>
                <%= image_tag post.photo.url(:search), :class => "img_border" %>
              <% end %>
            </td>
            <td><%= link_to post.user.name, {:controller => :admin, :action => :view_user, :id => post.user.id} %></td>
            <td>Coments (<%= post.comments.count %>)</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>

  <div class="row">
  <%= will_paginate @posts%>
  </div>
</div>

app/views/admin/view_problem_report.html.erb
<div class="row wrapper adminSection">  
	<h6>View Details For <%= @problem_report.exception_message %> </h6>

	<p><strong>ID:</strong> <%= @problem_report.id %></p>
	<p><strong>Created At</strong> <%= @problem_report.created_at %></p>
	<p><strong>Owned By</strong> <%= @problem_report.owner_name %></p>
	<p><strong>Status</strong> <%= @problem_report.status %></p>
	<p><strong>Exception Message:</strong> <%= @problem_report.exception_message %></p>
	<p><strong>Exception Class:</strong> <%= @problem_report.exception_class %></p>
	<p><strong>User Agent:</strong> <%= @problem_report.user_agent %></p>
	<p><strong>IP Address:</strong> <%= @problem_report.ip_address %></p>
	<p><strong>URL Referrer:</strong> <%= @problem_report.url_referrer %></p>
	<p><strong>User Signed In:</strong> <%= @problem_report.signed_in_user_name %></p>
	<p><strong>Last Updated At</strong> <%= @problem_report.updated_at %></p>
	<p><strong>Last Updated By</strong> <%= @problem_report.last_updated_by_name %></p>
	<p><strong>Exception Backtrace:</strong>
	  <% @problem_report.exception_backtrace.split('-').each do |line| %>
	      <% if not line.strip.blank? %>
	          <%= line %><br/>
	      <% end %>
	  <% end %>
	</p>
</div>

app/views/admin/view_user.html.erb
<section class="row wrapper adminSection">
  <div class="white_well col2 pull_right">
    <div class="row admin_controlls">
      <% if current_user.is_admin? && !current_user?(@user) && @user.is_active? %>
        <%= link_to "Ban", {:controller => :admin, :action => :set_user_status, :id => @user.id, :status => "BAN"}, class: "btn_red col6 pull_left", confirm: "Ban: You sure?" %>
        <%= link_to "Suspend", {:controller => :admin, :action => :set_user_status, :id => @user.id, :status => "SUS"}, class: "btn_yellow col6 .offset1 pull_left", confirm: "Suspend: You sure?" %>

      <% elsif current_user.is_admin? && !current_user?(@user) && @user.is_suspended? %>
        <%= link_to "Reenable", {:controller => :admin, :action => :set_user_status, :id => @user.id, :status => "ACT"}, class: "btn_green col6 pull_left", confirm: "Re-enable: You sure?" %>
        <%= link_to "Ban", {:controller => :admin, :action => :set_user_status, :id => @user.id, :status => "BAN"}, class: "btn_red col6 .offset1 pull_left", confirm: "Ban: You sure?" %>

      <% elsif current_user.is_admin? && !current_user?(@user) && @user.is_banned? %>
        <%= link_to "Reenable", {:controller => :admin, :action => :set_user_status, :id => @user.id, :status => "ACT"}, class: "btn_green col6 pull_left", confirm: "Re-enable: You sure?" %>

      <% end %>
    </div>
  </div>

  <div class="white_well col4 pull_left">
    <header class="row">
      <div class="col2 pull_left">
        <%= image_tag @user.profile_photo_url, style: "width: 80px;" %>
      </div>
      <div class="col4 pull_left">
        <h1>User (<%= @user.name %>)</h1>
        <h3>Status (<%= @user.status %>)</h3>
        <h4>User Profile Page: <%= link_to user_path(@user.name), user_path(@user.name) %></h4>
      </div>
    </header>

    <div class="row">

      <h3>Posts (<%= @userposts.count %>) </h3>

      <div class="row">
      <%= will_paginate @userposts%>
      </div>

        <section>
          <table class="admin_table table_bordered table-striped">
            <thead>
              <tr>
                <th></th>
                <th>Item</th>
                <th>Photo</th>
                <th>Status</th>
                <th>Open</th>
              </tr>
            </thead>
            <tbody>
              <% @userposts.each do |post| %>
                <tr>
                  <td><%= post.id %></td>
                  <td><%= link_to post.hashtag_prefix, {:controller => :admin, :action => :view_post, :id => post.id} %></td>
                  <td>
                    <% if post.photo_file_name.blank? %>
                      <%= image_tag "noPhoto_80x80.png" %>
                    <% else %>
                      <%= image_tag post.photo.url(:search), :class => "img_border" %>
                    <% end %>
                  </td>
                  <td><%= post.status %></td>
                  <td><%= post.open? %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </section>

        <div class="row">
        <%= will_paginate @userposts%>
        </div>

    </div>

    <br>

    <div class="row">

      <h3>Comments (<%= @usercomments.count %>) </h3>

      <div class="row">
      <%= will_paginate @usercomments%>
      </div>

      <section>
        <table class="admin_table table_bordered table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Content</th>
              <th>Post</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @usercomments.each do |comment| %>
              <tr>
                <td><%= comment.id %></td>
                <td><%= link_to comment.body, {:controller => :admin, :action => :view_comment, :id => comment.id} %></td>
                <td><%= link_to comment.post.hashtag_prefix, {:controller => :admin, :action => :view_post, :id => comment.post.id} %></td>
                <td><%= comment.status %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </section>

      <div class="row">
      <%= will_paginate @usercomments%>
      </div>
    </div>
  </div>

</section>

app/views/admin/view_users.html.erb
<div class="row wrapper adminSection">
  <h1>All users</h1>

  <div class="row">
  <%= will_paginate @users%>
  </div>

  <section class="row">
    <table class="admin_table table_bordered table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th></th>
          <th>Username</th>
          <th>Posts</th>
          <th>Comments</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %>
            <td><%= image_tag user.profile_photo_url %></td>
            <td><%= link_to user.name, {:controller => :admin, :action => :view_user, :id => user.id} %></td>
            <td>Posts (<%= user.posts.count %>)</td>
            <td>Comments (<%= user.comments.count %>)</td>
            <td><%= user.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>

  <div class="row">
  <%= will_paginate @users%>
</div>
</div>