config/routes.rb
SlinggitWebapp::Application.routes.draw do
  match 'users/set_no_thanks', :to => 'users#set_no_thanks', via: :get
  match 'users/reset_page_session', :to => 'users#reset_page_session', via: :get
  match 'users/verify_email_availability', :to => 'users#verify_email_availability', via: :post
  match 'users/verify_username_availability', :to => 'users#verify_username_availability', via: :post
  match 'users/update_email_and_send_verification', :to => 'users#update_email_and_send_verification', via: :put
  match '/edit_email_for_verification', :to => 'users#edit_user_email_for_verification', :as => 'prep_for_reverification'
  match 'networks/set_primary_account', :to => 'networks#set_primary_account', via: :post
  match 'posts/filtered_list', :to => 'posts#filtered_list'

  match 'users/email_preferences', :to => 'users#email_preferences'
  match 'users/enter_new_password/(:id)', :to => 'users#enter_new_password#id'
  match 'users/password_reset', :to => 'users#password_reset'
  match 'users/reactivate(/:id)', :to => 'users#reactivate#id', via: :get
  match 'users/destroy', :to => 'users#destroy', via: :delete
  match 'users/delete_account', :to => 'users#delete_account', via: :get
  match 'users/verify_email(/:id)', :to => 'users#verify_email#id'
  match 'users/new(/:id)', :to => 'users#new#id'
  match 'users/watching', :to => 'users#watching', as: "users_watching", via: :get
  match 'users/archived', to: 'users#archived', as: "users_archived", via: :get
  match 'networks/delete_account', :to => 'networks#delete_account', via: :post
  match 'networks/add_api_account(/:id)', :to => 'networks#add_api_account#id', via: :get
  match 'networks/twitter_callback', :to => 'networks#twitter_callback', via: :get
  match 'networks/facebook_callback', :to => 'networks#facebook_callback', via: :get
  match 'sessions/sign_out_of_device', :to => 'sessions#sign_out_of_device', via: :post
  match 'posts/results/(:id)', :to => 'posts#results#id', via: :get
  match 'posts/delete_post', :to => 'posts#delete_post'
  match 'posts/report_abuse(/:id)', :to => 'posts#report_abuse#id'
  match 'posts/repost(/:id)', :to => 'posts#repost#id'
  match 'posts/edit_field(/:id)', :to => 'posts#edit_field#id'
  match 'additional_photos/add', :to => 'additional_photos#add', :via => :post

  match 'watchedposts/interested', :to => 'watchedposts#interested'
  match 'watchedposts/uninterested', :to => 'watchedposts#uninterested'

  match 'messages/delete(/:id)', :to => 'messages#delete#id'
  match 'messages/delete_all', :to => 'messages#delete_all'
  match 'messages/new(/:id)', :to => 'messages#new#id'
  match 'messages/reply(/:id)', :to => 'messages#reply#id'
  match 'messages/sent', :to => 'messages#sent'

  resources :users
  resources :messages
  resources :sessions, only: [:new, :create, :destroy, :index]
  resources :posts, only: [:new, :create, :destroy, :edit, :show, :update]
  resources :networks, only: [:index, :create, :destroy]
  resources :watchedposts

  match '/twitter_callback', :to => 'twittersessions#callback', :as => 'callback'
  match '/facebook_callback', :to => 'facebooksessions#callback', :as => 'facebook_callback'
  match '/twitter_signup_callback', :to => 'users#twitter_signup_callback'
  match '/reauthorize_twitter', to: 'twittersessions#reauthorize'
  match '/create_reauthorization', to: 'twittersessions#create_reauthorization'
  match '/reauthorize_callback', to: 'twittersessions#reauthorize_callback'

  resources :twittersessions
  resource :facebooksessions

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/request_invitation', to: 'users#request_invitation', :as => 'request_invitation'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help', to: 'static_pages#help'
  match '/suspended_account', to: 'static_pages#suspended_account'
  match '/deleted_account', to: 'static_pages#deleted_account'
  match '/reactivate_account', to: 'static_pages#reactivate_account'
  match '/terms_of_service', to: 'static_pages#terms_of_service'

  resources :additional_photos
  resources :posts do
    resources :comments
  end
  match 'comments/delete(/:id)', :to => 'comments#delete#id'

  match 'mobile' => 'mobile#index'
  match 'mobile(/:action)(/:id)', :to => 'mobile#action#id'

  match 'admin' => 'admin#index', :as => :admin_dashboard
  match 'admin/users' => 'admin#view_users', :as => :admin_users
  match 'admin/users(/:id)' => 'admin#view_user#id', :as => :admin_user
  match 'admin/posts' => 'admin#view_posts', :as => :admin_posts
  match 'admin/post(/:id)', to: 'admin#view_post#id', :as => :admin_post
  match 'admin/comments' => 'admin#view_comments', :as => :admin_comments
  match 'admin/comment(/:id)', to: 'admin#view_comment#id', :as => :admin_comment
  match 'admin/view_database', to: 'admin#view_database', as: :admin_database
  match 'admin/problem_reports', to: 'admin#problem_reports', as: :admin_problem_reports
  match 'admin(/:action(/:id))' => 'admin#action#id'

  match 'test' => 'test#index'
  match 'test(/:action)(/:id)', :to => 'test#action#id'

  match 'backend/daily_jobs', :to => 'backend#daily_jobs'

  match '/maintenence', to: 'static_pages#maintenence', :as => 'maintenence'
  match '/over_capacity', to: 'static_pages#over_capacity', :as => 'over_capacity'

  match '*path', :to => 'application#redirect'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :destroy, :delete_account, :edit_user_email_for_verification, :update_email_and_send_verification, :email_preferences]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :user_verified, only: [:edit, :update, :destroy]

  # Method is in application_controller
  before_filter :set_cache_buster, only: [:edit_user_email_for_verification]

  # Controller specific, non-environement dependent, constants
  USERS_PATH = "/users"

  # CMK: Don't remember if I put this here or not, but will look at once we
  # start our async stuff
  #respond_to :json

  def index
    if signed_in?
      redirect_to current_user
    else
      redirect_to new_user_path
    end
  end

  def request_invitation

    #check to see if the user already exists in the users table as well

    if request.post?
      if not params[:email].blank?
        if invitation = Invitation.first(:conditions => ['email = ?', params[:email]], :select => 'status')
          if invitation.status == 'approved'
            flash.now[:notice] = "Your invitation has already been approved.  Please follow the link in your approval email."
          elsif invitation.status == 'active'
            flash.now[:notice] = "Your invitation has already been activated.  Please log in with your email and password"
          else
            flash.now[:notice] = "You have already requested an invitation.  We will let you know when it has been approved."
          end
        else
          #this will automatically generate an email for us and the user.
          Invitation.create(
              :email => params[:email],
              :comment => params[:comment]
          )
          flash.now[:success] = "Invitation request has been sent.  We will approve it as soon as possible."
          #redirect_to :controller => :static_pages, :action => :home
        end
      else
        flash.now[:error] = "Please give us your email address so we can contact you when your invitation is approved."
      end
    end
  end


  def show
    @label = "My"
    #@passes_limitation = nil
    @user = User.first(:conditions => ['name = ?', params[:id]])
    if signed_in?
      if current_user.id == @user.id
        @passes_limitation = passes_limitations?(:total_posts)
      end
    end
    if not @user.blank? and not @user.is_considered_deleted?
      #@posts = Post.all(:conditions => ['user_id = ? AND status = ? AND open = ?', @user.id, STATUS_ACTIVE, true])
      @posts = Post.paginate(page: params[:page], :per_page => 20, :conditions => ['user_id = ? AND status = ? AND open = ?', @user.id, STATUS_ACTIVE, true])
      #get_posts_for_user 'show', params[:page], 20, @user.id, STATUS_ACTIVE, true
    else
      if signed_in?
        redirect_to current_user
      else
        redirect_to new_user_path
      end
    end
  end

  def watched
  end

  def watching
    @label = "Watched"
    @passes_limitation = passes_limitations?(:total_posts)
    if signed_in? and params[:id] == current_user.name and not current_user.is_considered_deleted?
      @user = current_user
      @posts = []
      Watchedpost.find_each(:conditions => ['user_id = ?', @user.id], :select => 'post_id') do |watched_post|
        @posts << Post.first(:conditions => ['id = ?', watched_post.post_id])
      end
      @posts = @posts.paginate(:page => params[:page], :per_page => 20)
      render 'show'
    else
      redirect_to signin_path
    end
  end

  def archived
    @label = "Archived"
    @passes_limitation = passes_limitations?(:total_posts)
    if signed_in? and params[:id] == current_user.name and not current_user.is_considered_deleted?
      @user = current_user
      @posts = Post.paginate(page: params[:page], :per_page => 20, :conditions => ['user_id = ? AND status = ? AND open = ?', @user.id, STATUS_ACTIVE, false])
      render 'show'
    else
      redirect_to signin_path
    end
  end

  def new
    if invite_only? and params[:id].blank? and session[:approved_invitation].blank?
      flash[:notice] = "We are not currently accepting new users without an invitation."
      redirect_to :action => :request_invitation and return
    elsif invite_only? and not params[:id].blank?
      if invitation = Invitation.first(:conditions => ['activation_code = ?', params[:id]])
        session[:approved_invitation] = invitation
      else
        flash[:notice] = "We are sorry, but the invitation code provided is invalid."
        redirect_to :action => :request_invitation and return
      end
    end

    if session[:user].blank?
      @user = User.new
      if not session[:approved_invitation].blank?
        @user.email = session[:approved_invitation].email
      end
      # CMK: storing return_url here, prior to session reset, so that we can return
      # the use back to, say, a post if it's not nil.
      return_url = session[:return_to]
      approved_invitation = session[:approved_invitation]

      reset_session

      if return_url
        session[:return_to] = return_url
      end

      if approved_invitation
        session[:approved_invitation] = approved_invitation
      end
    else
      @user = session[:user]
      session.delete(:user)
    end
  end

  def create
    if not invite_only? or (invite_only? and not session[:approved_invitation].blank?)
      @user = User.new(params[:user])
      if not invite_only? or (invite_only? and @user.email == session[:approved_invitation].email)
        if not params[:twitter_authenticate].blank?
          success = validate_pre_twitter_data
          if success
            # CMK: so I added :return_url to parameters, so that we can have that after
            # twitter authentication, in order to redirect the use back to, say, a post.
            setup_twitter_call(url_for(:controller => :users, :action => :twitter_signup_callback, :name => @user.name, :email => @user.email, :return_url => session[:return_to]))
          else
            render 'new'
          end
        else
          if @user.save
            if not session['access_token'].blank? and not session['access_secret'].blank?
              client = Twitter::Client.new(oauth_token: session['access_token'], oauth_token_secret: session['access_secret'])
              create_api_account(:source => :twitter, :user_object => @user, :api_object => client)
              session.delete('access_token')
              session.delete('access_secret')
            end
            @user.update_attribute(:email_activation_code, Digest::SHA1.hexdigest(@user.email + "slinggit_email_activation_code" + SLINGGIT_SECRET_HASH))
            UserMailer.welcome_email(@user).deliver
            sign_in @user
            session.delete(:approved_invitation)
            flash[:success] = "Welcome SlingGit.  Please be sure to verify your email address."
            redirect_back_or @user
          else
            render 'new'
          end
        end
      else
        flash[:error] = "The email address you provided did not match the invitation request.  Please be sure to use the same email address you used when you requested an invite."
        redirect_to :action => :new
      end
    else
      flash[:notice] = "We are not currently accepting new users without an invitation."
      redirect_to :action => :request_invitation and return
    end
  end

  def edit_user_email_for_verification
    if current_user.status != STATUS_UNVERIFIED
      flash[:notice] = "You have already verfied your email with us."
      redirect_to user_path(current_user)
    end
  end

  def update_email_and_send_verification
    user_updates = params[:user]
    if current_user.update_attributes(user_updates)
      current_user.update_attribute(:email_activation_code, Digest::SHA1.hexdigest(current_user.email + "slinggit_email_activation_code" + SLINGGIT_SECRET_HASH))
      UserMailer.welcome_email(current_user).deliver
      flash[:success] = "A verification email has been sent to #{current_user.email}"
      redirect_to user_path(current_user)
    else
      render 'edit_user_email_for_verification'
    end
  end

  def edit
  end

  def update
    # @user = User.find(params[:id])  !Not needed because of :correct_user before_filter

    # we dont want to force the user to pass in all attributes, but rather, just the ones they want to change
    user_updates = params[:user]
    user_updates.delete_if { |key, value| value.blank? }

    if @user.update_attributes(user_updates)
      flash[:success] = "Profile updated"
      sign_in @user
      reset_session
      redirect_to @user
    else
      render 'edit'
    end
  end

  def email_preferences
    @email_preference = EmailPreference.first(:conditions => ['user_id = ?', current_user.id])
    if not @email_preference.blank?
      if request.post?
        if not params[:system_emails].blank? and params[:system_emails] == '1'
          @email_preference.system_emails = true
        else
          @email_preference.system_emails = false
        end
        if not params[:marketing_emails].blank? and params[:marketing_emails] == '1'
          @email_preference.marketing_emails = true
        else
          @email_preference.marketing_emails = false
        end
        @email_preference.save
        flash[:success] = "Email preferences updates"
      end
    else
      flash[:error] = "Oops, something has gone wrong.  Please try again later."
      redirect_to @user
    end
  end

  def verify_email
    if not params[:id].blank?
      if user = User.first(:conditions => ['email_activation_code = ?', params[:id]])
        if user.email_activation_code == Digest::SHA1.hexdigest(user.email + "slinggit_email_activation_code" + SLINGGIT_SECRET_HASH)
          user.update_attribute(:email_activation_code, nil)
          user.update_attribute(:status, STATUS_ACTIVE)
          flash[:success] = "Your email has been verified."
          sign_in user
          redirect_to user
        else

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  # HEADS UP!! The id for the image tag is needed!
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://gravatar.com/avatar/#{gravatar_id}.png"
    image_tag(gravatar_url, alt: user.name , id: "GPS", class: "gravatar", :height => "auto", :width => "100%", :style => "max-width: 80px;")
  end

  # Generic method for creating post feeds to be shown on the user show page.  
  # Might even be able to abstract this to application helper something so
  # that it can be used with seaches and what not.
  def get_posts_for_user filter, page, per_page, user_id, status, open
    if filter == "open"
      @posts = Post.paginate(page: page, :per_page => per_page, :conditions => ['user_id = ? AND status = ? AND open = ?', user_id, status, open])
    elsif filter == "watched"
      @posts = []
      Watchedpost.find_each(:conditions => ['user_id = ?', user_id], :select => 'post_id') do |watched_post|
        @posts << Post.first(:conditions => ['id = ?', watched_post.post_id])
      end
      @posts = @posts.paginate(:page => params[:page], :per_page => 20)
    elsif filter == "archived"
      @posts = Post.paginate(page: params[:page], :per_page => 20, :conditions => ['user_id = ? AND status = ? AND open = ?', user_id, STATUS_ACTIVE, false]) 
    else

    end
  end

end

app/views/users/_add_more_networks.html.erb
<div id="add_more_networks" class="row grey_well">
	<p>Social networks provide the platform you need to broaden your reach to potential buyers and significantly shorten the sales cycle.</p>

	<div class="col3 pull_left">
	<% if @user.primary_twitter_account.blank? %>
		<%= link_to "Add Twitter Account", url_for(:controller => :networks, :action => :add_api_account, :id => 'twitter'), class: "btn btn_twitter col6", :id => 'addTwitterbutton' %>
	<% end %>
	</div>
	
	<div class="col3 pull_left">
	<% if @user.primary_facebook_account.blank? %>
		<%= link_to "Add Facebook Account", url_for(:controller => :networks, :action => :add_api_account, :id => 'facebook'), class: "btn btn_facebook col6", :id => 'addFacebookbutton' %>
	<% end %>
	</div>

</div>

app/views/users/_select_photo.html.erb
<div id="photoSelectorWrapper" class="grey_well">
	
	<div class="row">
		<div class="col6">
			<p>Select your profile photo</p>
		</div>
	</div>

	<%= form_for(@user) do |f| %>
		<div class="row">
			<div class="col2 pull_left">
				<div class="row">
					<%= image_tag "icon_blue_80x80.png", id: "SPS" %>
				</div>
				<div class="row">
					<p>Slinggit</p>
				</div>
			</div>

			<% if not @user.primary_twitter_account.blank? %>
				<div class="col2 pull_left">
					<div class="row">
						<%= image_tag @user.primary_twitter_account.image_url, id: "TPS" %>
					</div>
					<div class="row">
						<p>Twitter</p>
					</div>
				</div>
			<% end %>
			
			<% if not @user.primary_facebook_account.blank? %>
				<div class="col2 pull_left">
					<div class="row">
						<%= image_tag @user.primary_facebook_account.image_url, id: "FPS" %>
					</div>
					<div class="row">
						<p>Facebook</p>
					</div>
				</div>
			<% end %>

			<div class="col2 pull_left">
				<div class="row">
					<%= gravatar_for @user %>
				</div>
				<div class="row">
					<p>Gravatar | <a href="https://gravatar.com/emails" target="_blank">change</a></p>
				</div>
			</div>
		</div>
		<%= f.hidden_field :photo_source %>
	<% end %>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		window.initPhotoSelector("<%= @user.id %>", true)
	})
</script>

app/views/users/delete_account.html.erb
<% provide(:title, "Delete Account") %>

<br/>
<section class="wrapper page_col singleWide">
  <header>
    <h1>Delete Your Account</h1>
  </header>

  <%= form_tag(url_for(:controller => :users, :action => :destroy), :method => :delete) do %>
      <p class='subHeader'>1. In order to delete your account, we need to verify your password.</p>
      <%= password_field_tag :password, nil, :placeholder => 'Password', class: "input-xlarge" %>
      <span id="passwordEntryNotification"></span>

      <p class='subHeader'>2. By clicking Delete My Account, you are acknowledging that the below statements are
        true:</p><br/>
      <ul id="deleteConsequenceList">
        <li>All of your posts will be deleted and become unsearchable, undiscoverable and unviewable by all other
          customers.
        </li>
        <li>You will no longer be able to create new posts or view other customer posts.</li>
        <li>Tweets created on your Twitter account will not be removed.</li>
        <li>Some information will be retained for account reactivation should you change your mind.</li>
        <li>You will receive a confirmation email with a reactivation link that can be used at any time.</li>
        <li>You will be immidiately signed out after we have finished deleting your account.</li>
      </ul>

      <br/>
      <p class='subHeader'>3. We will read what you have to say. So, speak your mind, be brutally honest and let us know
        why are you deleting your account?</p>
      <%= text_area_tag :reason, @reason, :placeholder => 'Example: "I dislike the color blue."', class: "input-xlarge", :style => 'width:100%;' %>

      <div class="row">
        <div class="col6">
          <%= button_tag "Delete My Account", :type => "submit", class: "btn btn_red", :id => 'delete_account', :title => "Do you acknowledge everything on this page and still want to delete your account?" %>
          <%= link_to "Cancel", edit_user_path(current_user), :class => "btn" %>
        </div>
      </div>
  <% end %>

</section>

<script type="text/javascript">
    $(document).ready(function () {
        $('#password').keyup(function () {
            $("#passwordEntryNotification").html('')
        });

        $('#delete_account').easyconfirm({locale:{ title:'Confirm Account Deletion', button:['No', 'Yes - Delete My Account']}});
        $('#delete_account').click(function (e) {
            e.preventDefault();
            if ($('#password').val().length > 0) {
                $('form').submit();
            } else {
                $("#passwordEntryNotification").html("<span id=\"error_explanation\"><ul><li>* You must first enter your password.</li></ul></span>");
            }
        });
    })
</script>

<style type="text/css">
    ul#deleteConsequenceList {
        list-style: disc inside none;
        font-size: 1.6em;
        line-height: 1.2em;
        padding-left: 20px;
    }
</style>

app/views/users/edit_user_email_for_verification.html.erb
<% provide(:title, "Request Verification Email") %>
<section id="emailVerificationWrapper" class="wrapper">
	<div class="row">
		<header>
			<h1>Request new verification email</h1>
		</header>
	</div>
	<div class="row white_well">
		<div class="col3">
		<%= form_for current_user, :url => {:action => "update_email_and_send_verification"} do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.hidden_field :id %>

            <fieldset class="row">
				<p><strong><%= current_user.name %></strong>, please make sure that this is the correct email address prior to requesting a new verification email.</p>
				<%= f.text_field :email, class: "col6 form_singleLine" %>
			</fieldset>

            <%= f.submit "Send Email", class: "btn_ltGrey" %>
		<% end %>
	</div>
	</div>

</section>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<section class="wrapper wrapper_newUser white_well">
	<header class="row">
		<h1 class="bottom_border">Sign up</h1>
	</header>

<div class="col3 well">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		
<!-- user name -->
		<fieldset class="row">
			<%= f.label :name, "Username", for: "user_name", class: "col6" %>
			<%= f.text_field :name, placeholder: "Username", class: "col6" %>
			<div class="col6" id="usernameAvailabilityNotification"></div>
		</fieldset>
<!-- end -->

<!-- email -->
		<fieldset class="row">
			<%= f.label :email, for: "user_email", class: "col6" %>
			<%= f.email_field :email, placeholder: "Email", class: "col6" %>
			<div class="col6" id="emailAvailabilityNotification"></div>
		</fieldset>
<!-- end -->

<!-- authenticate buttons -->
		<fieldset class="row form-actions" id="form_signUpActions">
			<%= link_to("#", :class => "col3 pull_left btn_twitter ss-twitter ss-social", :onclick => "javascript:void(0)", :id => "twitterBTN") do %>
				Sign Up with Twitter
			<% end %>
	
			<%= f.button "No Twitter", type: "button", class: "col2 pull_right btn_ltGrey", onclick: "javascript:void(0)", id: 'noThanksBTN' %>
			<%= hidden_field_tag :twitter_authenticate, nil %>
		</fieldset>
<!-- end -->

<!-- password field -->
	<fieldset class="row form_hiddenFields">
		<%= f.label :password, "Slinggit Password", for: "user_password", class: "col6" %>
		<%= f.password_field :password, placeholder: "Password", class: "col6" %>
	</fieldset>
<!-- end -->

<!-- password confirm -->
	<fieldset class="row form_hiddenFields">
		<%= f.label :password_confirmation, "Confirm Password", for: "user_password_confirmation", class: "col6" %>
		<%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "col6" %>
	</fieldset>
<!-- end -->

<!-- submit -->
	<fieldset class="row form_hiddenFields">
		<%= f.button "Create my account", class: "col3 pull_left btn_green" %>
		<%= link_to 'start over', nil, :onclick => "javascript:void(0)", class: "col2 pull_right", :id => 'signUpStartOverLink' %>
		<div class="row termsOfService">
			<small>By signing into Slinggit. You agree to our <%= link_to "Terms of Service", terms_of_service_path %>.</small>
		</div>
	</fieldset>

<!-- end -->
	<% end %>
</div>
</section>

<script>
    $(document).ready(function () {
        window.emailValidationView(
            "<%= url_for :controller => :users, :action => :verify_email_availability %>"
          , "<%= url_for :controller => :users, :action => :verify_username_availability %>"
          , "<%= url_for :controller => :users, :action => :reset_page_session %>"
          , "<%= url_for :controller => :users, :action => :set_no_thanks %>"
          , "<%= session[:twitter_permission_granted] %>"
          , "<%= session[:no_thanks]%>"
        )
    });

</script>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<section id="userPostsWrapper" class="wrapper">

  <section class="secondary">

    <div class="secondary_inner">

      <aside class="userInfo row">
        <a href="<%= user_path(@user) %>" class="col2 pull_left">      
          <%= image_tag @user.profile_photo_url, :height => "auto", :width => "100%" %>
        </a>
        <header class="col4 pull_right">
          <h1 class="bottom_border"><%= @user.name %></h1>
            <dl class="dl-horizontal">
              <dt>Open Posts:</dt> <dd><%= @user.open_post_count %></dd>
              <dt>Posts Remaining:</dt> <dd><%= (@user.post_limit) - (@user.open_post_count) %></dd>
              <dt>Open Post Limit:</dt> <dd><%= @user.post_limit %></dd>
            </dl>
        </header>

        <% if is_signed_in_and_admin? && !current_user?(@user) %>
            <div class="row adminActions">
              <!-- ADMIN ONLY FUNCTIONALITY -->
                <%= link_to "Admin", {:controller => :admin, :action => :go_to_admin_resource, :id => @user.id, :resource => "user"} %>
            </div>
          <% end %>
      </aside>

    </div>


      <% if current_user?(@user) and not current_user.is_suspended? and current_user.email_is_verified? %>        

        <div class="secondary_inner">

          <section class="secondary_actions">
            
            <div id="createPostAction" class="row">
              <% if @passes_limitation != nil and @passes_limitation == true %>
                <%= link_to "New Post", new_post_path, class: "ss-compose col6 btn_green" %>
              <% elsif @passes_limitation[0] == false %>
                <p class="row notice_explanation_bubble">Post Limit Reached</p>
              <% end %>
            </div>

            <div id="postsFilters" class="row" style="margin-top: 20px;">
              <a href="#posted" class="col6 active" id="posted">
                Posted <span class='nav_arrow pull_right'>&rarr;</span>
              </a>
              <a href="#watching" class="col6" id="watching">
                Watching <span class='nav_arrow pull_right'>&rarr;</span>
              </a>
              <a href="#archived" class="col6" id="archived">
                Archived <span class='nav_arrow pull_right'>&rarr;</span>
              </a>
            </div>

          </section>

        </div>

    <% end %>

  </section>

	<section id="userPosts" class="main">
    <div class="row title_row">
      <div class="col6 pull_left">
        <div class="row">
          <header>
          </header>
        </div>

        <% if current_user?(@user) %>        

          <% if not current_user.is_suspended? %>

            <% if current_user.email_is_verified? %>
              <% if !@user.has_photo_source? && current_user?(@user) %>
                  <%= render 'users/select_photo' %>
              <% end %>
              <% if !@user.posts.any? and (@user.primary_twitter_account.blank? or @user.primary_facebook_account.blank?) %>
                <%= render 'users/add_more_networks' %>
              <% end %>
            <% else %>
              <div class="row unverified_user">
                <p><span class="user-name"><%= current_user.name %></span>, before you begin posting, we need you to verify your
                  email address.</p>

                <p>If you haven't recieved an email from us, check your <span class="notice">spam folder</span> or you can always have
                  us <%= link_to "resend it.", prep_for_reverification_path %></p>
              </div> 
            <% end %>

          <% end %>

        <% end %>
      </div>
    </div>

    <div id="postArticlesWrapper">
    </div>

  </section>


</section>

<%= content_tag "div", "", id: "userJson", data: {user: render(template: 'users/show', formats: [:json], handlers: [:jbuilder])} %>
<script>
  $(document).ready(function(){
    Slinggit.initUsersShow()
  })
</script>