config/routes.rb
SlinggitWebapp::Application.routes.draw do
  match 'users/set_no_thanks', :to => 'users#set_no_thanks', via: :get
  match 'users/reset_page_session', :to => 'users#reset_page_session', via: :get
  match 'users/verify_email_availability', :to => 'users#verify_email_availability', via: :post
  match 'users/verify_username_availability', :to => 'users#verify_username_availability', via: :post
  match 'users/update_email_and_send_verification', :to => 'users#update_email_and_send_verification', via: :put
  match '/edit_email_for_verification', :to => 'users#edit_user_email_for_verification', :as => 'prep_for_reverification'
  match 'networks/set_primary_account', :to => 'networks#set_primary_account', via: :post
  match 'posts/filtered_list', :to => 'posts#filtered_list'

  match 'users/email_preferences', :to => 'users#email_preferences'
  match 'users/enter_new_password/(:id)', :to => 'users#enter_new_password#id'
  match 'users/password_reset', :to => 'users#password_reset'
  match 'users/reactivate(/:id)', :to => 'users#reactivate#id', via: :get
  match 'users/destroy', :to => 'users#destroy', via: :delete
  match 'users/delete_account', :to => 'users#delete_account', via: :get
  match 'users/verify_email(/:id)', :to => 'users#verify_email#id'
  match 'users/new(/:id)', :to => 'users#new#id'
  match 'users/watching', :to => 'users#watching', as: "users_watching", via: :get
  match 'users/archived', to: 'users#archived', as: "users_archived", via: :get
  match 'networks/delete_account', :to => 'networks#delete_account', via: :post
  match 'networks/add_api_account(/:id)', :to => 'networks#add_api_account#id', via: :get
  match 'networks/twitter_callback', :to => 'networks#twitter_callback', via: :get
  match 'networks/facebook_callback', :to => 'networks#facebook_callback', via: :get
  match 'sessions/sign_out_of_device', :to => 'sessions#sign_out_of_device', via: :post
  match 'posts/results/(:id)', :to => 'posts#results#id', via: :get
  match 'posts/delete_post', :to => 'posts#delete_post'
  match 'posts/report_abuse(/:id)', :to => 'posts#report_abuse#id'
  match 'posts/repost(/:id)', :to => 'posts#repost#id'
  match 'posts/edit_field(/:id)', :to => 'posts#edit_field#id'
  match 'additional_photos/add', :to => 'additional_photos#add', :via => :post

  match 'watchedposts/interested', :to => 'watchedposts#interested'
  match 'watchedposts/uninterested', :to => 'watchedposts#uninterested'

  match 'messages/delete(/:id)', :to => 'messages#delete#id'
  match 'messages/delete_all', :to => 'messages#delete_all'
  match 'messages/new(/:id)', :to => 'messages#new#id'
  match 'messages/reply(/:id)', :to => 'messages#reply#id'
  match 'messages/sent', :to => 'messages#sent'

  resources :users
  resources :messages
  resources :sessions, only: [:new, :create, :destroy, :index]
  resources :posts, only: [:new, :create, :destroy, :edit, :show, :update]
  resources :networks, only: [:index, :create, :destroy]
  resources :watchedposts

  match '/twitter_callback', :to => 'twittersessions#callback', :as => 'callback'
  match '/facebook_callback', :to => 'facebooksessions#callback', :as => 'facebook_callback'
  match '/twitter_signup_callback', :to => 'users#twitter_signup_callback'
  match '/reauthorize_twitter', to: 'twittersessions#reauthorize'
  match '/create_reauthorization', to: 'twittersessions#create_reauthorization'
  match '/reauthorize_callback', to: 'twittersessions#reauthorize_callback'

  resources :twittersessions
  resource :facebooksessions

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/request_invitation', to: 'users#request_invitation', :as => 'request_invitation'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help', to: 'static_pages#help'
  match '/suspended_account', to: 'static_pages#suspended_account'
  match '/deleted_account', to: 'static_pages#deleted_account'
  match '/reactivate_account', to: 'static_pages#reactivate_account'
  match '/terms_of_service', to: 'static_pages#terms_of_service'

  resources :additional_photos
  resources :posts do
    resources :comments
  end
  match 'comments/delete(/:id)', :to => 'comments#delete#id'

  match 'mobile' => 'mobile#index'
  match 'mobile(/:action)(/:id)', :to => 'mobile#action#id'

  match 'admin' => 'admin#index', :as => :admin_dashboard
  match 'admin/users' => 'admin#view_users', :as => :admin_users
  match 'admin/users(/:id)' => 'admin#view_user#id', :as => :admin_user
  match 'admin/posts' => 'admin#view_posts', :as => :admin_posts
  match 'admin/post(/:id)', to: 'admin#view_post#id', :as => :admin_post
  match 'admin/comments' => 'admin#view_comments', :as => :admin_comments
  match 'admin/comment(/:id)', to: 'admin#view_comment#id', :as => :admin_comment
  match 'admin/view_database', to: 'admin#view_database', as: :admin_database
  match 'admin/problem_reports', to: 'admin#problem_reports', as: :admin_problem_reports
  match 'admin(/:action(/:id))' => 'admin#action#id'

  match 'test' => 'test#index'
  match 'test(/:action)(/:id)', :to => 'test#action#id'

  match 'backend/daily_jobs', :to => 'backend#daily_jobs'

  match '/maintenence', to: 'static_pages#maintenence', :as => 'maintenence'
  match '/over_capacity', to: 'static_pages#over_capacity', :as => 'over_capacity'

  match '*path', :to => 'application#redirect'

end

app/views/layouts/_admin_footer.html.erb
<footer class="adminFooter">
  <div class="wrapper">
    <div id="loggedInAs">
      <p>Logged in as: <%= current_user.name %></p>
      <table border="1">
        <tr>
          <td>id</td>
          <td><%= current_user.id %></td>
        </tr>
        <tr>
          <td>email</td>
          <td><%= current_user.email %></td>
        </tr>
        <tr>
          <td>account status</td>
          <td><%= current_user.status %></td>
        </tr>
        <tr>
          <td>created on</td>
          <td><%= current_user.created_at %></td>
        </tr>
      </table>
    </div>
  </div>
</footer>

app/views/layouts/_admin_header.html.erb
<header id="mainHeader" class="headerUp row">
  
<div class="row wrapper">
<!-- LOGO -->
    <hgroup class="col2 pull_left">
      <h1>Slinggit</h1>
<%= link_to image_tag('logos/slinggit_logotype_blue_417x162.png', width: '100%', height: 'auto', title: 'Slinggit Logo blue', alt: 'Slinggit Logo'), {:action => 'home', :controller => 'static_pages'}, class: 'row' %>
      <h6>beta</h6>
    </hgroup>
<!-- END LOGO -->

<!-- NAV GROUP -->
    <nav class="col4 pull_left">
<!-- NAV BUTTONS WRAPPER -->
      <div class="row">

 <!-- INDEX -->  
        <%= link_to admin_dashboard_path, class: "col2 pull_left #{'active' if current_page?(admin_dashboard_path)}" do %>
          Dashboard
        <% end %>
<!-- END INDEX -->

<!-- USERS -->
        <%= link_to admin_users_path, class: "col2 pull_left #{'active' if current_page?(admin_users_path)}" do %>
        Users
        <% end %>
<!-- END USERS -->

<!-- POSTS -->
        <%= link_to admin_posts_path, class: "col2 pull_left #{'active' if current_page?(admin_posts_path)}" do %>
        Posts
        <% end %>
<!-- END POSTS -->

<!-- COMMENTS -->
        <%= link_to admin_comments_path, class: "col2 pull_left #{'active' if current_page?(admin_comments_path)}" do %>
        Comments
        <% end %>
<!-- END COMMENTS -->

<!-- PROBLEM REPORTS -->  
        <%= link_to admin_problem_reports_path, class: "col2 pull_left #{'active' if current_page?(admin_problem_reports_path)}" do %>
          Problem Reports
        <% end %>
<!-- END PROBLEM REPORTS -->

<!-- DATABASE -->  
        <%= link_to admin_database_path, class: "col2 pull_left #{'active' if current_page?(admin_database_path)}" do %>
          Database
        <% end %>
<!-- END DATABASE -->

    </nav>
<!-- END RIGHT NAV GROUP -->

</header>
<!-- END HEADER -->

<script type="text/javascript">
    $(document).ready(function () {
        $('.BTN_nav_dropDown').dropdown()
        window.quickSearchView()
        window.initiHeaderSearch()
    });
</script>

app/views/layouts/_footer.html.erb
<footer class="pageFoot">
	<div class="wrapper">

		<nav class="col3 pull_left">
			<ul class="row">
				<li class="pull_left">
					<%= link_to "About", about_path %>
				</li>
				<li class="pull_left">
					<%= link_to "Contact", contact_path %>
				</li>
				<li class="pull_left">
					<%= link_to "Help", help_path %>
				</li>
				<!-- <li class="pull_left col1 <%= 'active' if current_page?(sessions_path) %>">
					<%= link_to "Sessions", sessions_path %>
				</li> -->
				<li class="pull_left">
					<%= link_to "Terms", terms_of_service_path %>
				</li>
				<li class="pull_left">
					<%= link_to "Home", :action => 'home', :controller => 'static_pages' %>
				</li>
			</ul>
			<ul class="row">
				<li class="pull_left col2">
					<a href="https://twitter.com/slinggit" title="Twitter" class="ss-twitter ss-social" >Twitter</a>
				</li>
				<li class="pull_left col2">
					<a href="https://www.facebook.com/Slinggit" title="Facebook" class="ss-facebook ss-social">Facebook</a>
				</li>
				<li class="pull_left col2">
					<a href="http://blog.slinggit.com/" title="Blog" class="ss-tumblr ss-social">Tumblr</a>
				</li>
			</ul>
		</nav>
		<div class="col3 pull_right">
		    <div class="row footerSignIn">
		   		<% if signed_in? %>
					<%= "#{current_user.name}" %> (<%= link_to "Sign out", signout_path, method: "delete" %>)
		      	<% else %>
					<%= link_to "Sign In", signin_path %>
	      		<% end %>
			</div>
			<div class="row">
		    	<small class="pull_right">&copy;2012 Slinggit, LLC</small>
				<%= link_to(about_path, :class => "pull_left") do %>
					<span class="coloradoIcon pull_left"></span>
					<small class="pull_left">Built in Denver, CO</small>
				<% end %>
			</div>
		</div>
<!--
<%= debug(params) if Rails.env.development? %>
-->
	</div>
</footer>

app/views/layouts/_header.html.erb
<header id="mainHeader" class="row">
  <div class="wrapper">
<div class="row">
<!-- LOGO -->
    <hgroup class="col2 pull_left">
      <h1>Slinggit</h1>

      <!--[if lt IE 9]>
		<%= link_to "", {:action => 'home', :controller => 'static_pages'}, class: 'row ie_logo_hack' %>
      <![endif]-->
      <!--[if gt IE 9]><!-->
		<%= link_to image_tag('logos/slinggit_logotype_blue_417x162.png', width: '100%', height: 'auto', title: 'Slinggit Logo blue', alt: 'Slinggit Logo'), {:action => 'home', :controller => 'static_pages'}, class: 'row' %>
	  <!--<![endif]-->
      <!-- <small>beta</small> -->
    </hgroup>
<!-- END LOGO -->

      <% if signed_in? %>

<!-- NAV GROUP -->
    <nav class="col4 pull_left">
<!-- NAV BUTTONS WRAPPER -->
              <div class="row">
<!-- POSTS -->	
				<%= link_to current_user, class: "col2 pull_left #{'active' if current_page?(current_user) || current_page?(users_watching_path) || current_page?(users_archived_path)}" do %>
					<span class="ss-home"></span>
					Home
				<% end %>
<!-- END POSTS -->

<!-- MESSAGES -->
				<%= link_to messages_path, class: "col2 pull_left #{'active' if current_page?(messages_path)}" do %>
					<span class="ss-inbox"></span>
					<%= "Messages#{(count = Message.count(:conditions => ['recipient_user_id = ? AND status = ?', current_user.id, STATUS_UNREAD])) > 0 ? ': ' + count.to_s + '' : ''}" %>
				<% end %>
<!-- END MESSAGES -->

<!-- SEARCH ICON -->
				<div class="col2 pull_left quickSearchLabel">
					<span class="ss-search"></span>
					<span>Search</span>
				</div>
<!-- END SEARCH ICON -->

<!-- DROP DOWN -->
				<div id="accountDropDown" class="dropdown col2 pull_left" %>
					<div class="dropdown-toggle" data-toggle="dropdown">
						<span class="ss-settings"></span>
						Settings
					</div>
					
					<ul class="nav_dropDown dropdown-menu">	
						<li class="<%= 'active' if current_page?(edit_user_path(current_user)) %>">
            				<%= link_to "Profile", edit_user_path(current_user) %>
            			</li>
                    	
						<li class="<%= 'active' if current_page?(networks_path) %>">
							<%= link_to "Social Networks", networks_path %>
            			</li>

            			<li>
                			<%= link_to "Email Preferences", :action => 'email_preferences', :controller => 'users' %>
              			</li>
                    	
						<li>
               				<%= link_to "Sign Out", signout_path, method: "delete" %>
            			</li>

						<% if current_user.is_admin? %>
							<li class="<%= 'active' if current_page?(users_path) %>">
							<%= link_to "Admin", admin_dashboard_path %>
							</li>
						<% end %>
                  	</ul>
                </div>
<!-- END DROP DOWN -->
              </div>
<!-- END BUTTON WRAPPER -->
    </nav>
<!-- END RIGHT NAV GROUP -->

<!-- ELSE IF signed_in? -->
      <% else %>

        <div class="col4 pull_left" id="header_signIn">
              <div class="row">
				<%= link_to signin_path, class: "col2 pull_left" do%>
					<span class="ss-user"></span>
					Sign In
				<% end %>
				<!-- SEARCH ICON -->
				<div class="col2 pull_right quickSearchLabel">
					<span class="ss-search"></span>
					<span>Search</span>
				</div>
				<!-- END SEARCH ICON -->
			</div>
        </div>
      <% end %>
<!-- END ELSE IF -->
  </div>
<!-- END ROW WRAPPER -->

<!-- QUICK SEARCH -->
      <div class="hideSearch row" id="quickSearchWrapper">
        <div class="col3 pull_right">
			<span class="ss-search pull_left"></span>
          <%= text_field_tag :quickSearch, nil, :placeholder => 'Quick Search', :name => 'quickSearch', :size => 'auto' %>
        </div>
      </div>
<!-- END QUICK SEARCH -->
	</div>
</header>
<!-- END HEADER -->

<script type="text/javascript">
    $(document).ready(function () {
        $('.BTN_nav_dropDown').dropdown()
        window.quickSearchView()
		window.initiHeaderSearch()
    });

</script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag "favicon.ico" %>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/admin_header' %>
<div class="page_contentContainer">
  <% flash.each do |key, value| %>
      <div id="<%= key %>_explanation">
        <div class="alert alert-<%= key %>"><%= value %></div>
      </div>
  <% end %>
  <%= yield %>
</div>
<%= render 'layouts/admin_footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag "favicon.ico" %>
  <!--[if lt IE 9]>
  <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <title><%= full_title(yield(:title)) %></title>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, maximum-scale=1" />
	<meta name="viewport" content="target-densitydpi=medium-dpi" />

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- GOOGLE ANALYTICS - KEEP AS LAST THING BEFORE CLOSING HEAD !-->
  <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-32813149-1']);
      _gaq.push(['_setDomainName', 'slinggit.com']);
      _gaq.push(['_trackPageview']);

      (function () {
          var ga = document.createElement('script');
          ga.type = 'text/javascript';
          ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(ga, s);
      })();

  </script>
  <!-- END GOOGLE ANALYTICS !-->

</head>

<body>
<%= render 'layouts/header' %>
<div class="page_contentContainer">
  <% flash.each do |key, value| %>
      <div id="<%= key %>_explanation_bubble">
        <div class="alert alert-<%= key %>"><%= value %></div>
      </div>
  <% end %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>

</html>